define({
    "loginBtn": "Log in",
    "registerBtn": "Create new account",
    "or": "or",
    "logoutBtn": "Logout",
    "profileBtn": "Profile",
    "support": "Support",
    "supportSite": "Gaijin support",
    "help": "Help!",
    "games": "Games",
    "store": "Store",
    "forum": "Forum",
    "language": "Language",
    "changePassword": "Change password",
    "purchaseHistory": "Purchase History",
    "en": "english",
    "ru": "русский",
    "de": "deutsch",
    "fr": "français",
    "it": "italiano",
    "es": "español",
    "ja": "日本語",
    "ko": "한국어",
    "pl": "polski",
    "cs": "čeština",
    "pt": "português",
    "tr": "türkçe",
    "zh": "中文",
    "go_url": "storefront.php?skin_lang=en",
    "wt_url": "//warthunder.com",
    "forum_wt_url": "//forum.warthunder.com",
    "wiki_wt_url": "//wiki.warthunder.com",
    "sc_url": "//star-conflict.com/en",
    "forum_sc_url": "//forum.star-conflict.com",
    "wiki_sc_url": "//wiki.star-conflict.com",
    "xo_url": "//crossout.net/en",
    "forum_xo_url": "//forum.crossout.net",
    "enl_url": "//enlisted.net/en/",
    "cr_url": "//crsed.net/en/",
    "live_url": "//live.warthunder.com/?lang=en",
    "support_url": "//support.gaijin.net/hc/en-us",
    "profile_link": "user.php?skin_lang=en",
    "changeAccount": "Switch account",
    "gaijin_link": "//gaijin.net/en",
    "site": "Site",
    "warning": "All informational email messages are switched off.",
    "critical": "Warning: security notifications are switched off.",
    "settingsText": "Manage settings"
});